---
- name: install vbox
  hosts: demo
  tasks:
  - name: install-vbox
    block:
      - name: install-vbox
        apt:
          name:
            - virtualbox
          update_cache: true 
          cache_valid_time: 86400
        become: true
        register: error
      
      - name: show error
        debug:
          msg:
          - "{{ error }}"

      
      - name: start_service
        service:
          name: virtualbox
          state: started
          enabled: true
        become: true
                       
      - name: install_vagrant
        apt:
          name: vagrant
          update-cache: true
        become: true
        
      - name: add vagrant_dir   
        command: mkdir /home/monik/vag
        command: touch /home/monik/vag/Vagrantfile
        
       

