---
- name: istall docker
  hosts: cluster
  
  tasks:
    - name: install form apt
      apt:
        name:
        - docker
        - docker.io
        - docker-compose
        - docker-registry
        update_cache: true 
        cache_valid_time: 86400
      become: true
    - name: add_user1
      shell:
        cmd: sudo groupadd docker & sudo usermod -aG docker $USER
      become: yes
  
      